pkg/controller/postgresql/grant/reconciler.go

Another RDS gotcha - `pg_authid` is not available to non-superusers as it contains a password field (unused in the queries that we make).
`pg_roles` is a publicly accessible view into the same underlying data, without the password field, and must be used if provisioning using the `postgres` user on RDS. There is no downside to switching to this when using a real superuser.
Signed-off-by: Ben Agricola <bagricola@squiz.co.uk>
Changed all instances of `pg_authid` table usage to `pg_roles` as we don't use the password field.
I have:
Passes the test suite locally, and has been verified against the same RDS cluster that was causing the issue originally (first log line is from provider without this fix):
```
Events:
Type     Reason                         Age                  From …
```

Use pg_roles to lookup postgres grants

---

pkg/controller/postgresql/role/reconciler.go

This one is a doozy by me - the role deletion query was missing a space, causing an SQL syntax error - however I missed this... because I had `deletionPolicy: Orphan` specified in my test resources 🤦
I have:
Code has been tested against a real RDS instance, querying `pg_roles` to confirm successful deletion (with `deletionPolicy: Delete`) after deleting the managed resource. Tests still pass locally.

Fix a typo in the role deletion query

---

apis/mysql/v1alpha1/grant_types.go
apis/postgresql/v1alpha1/grant_types.go

It appears that Resolving references from Selectors has not worked previously for either the MySQL or PostgreSQL Grant types. This is down to missing references to `List` for each referenced type, and potentially, not setting the `Ref` field to the resolved reference.
This commit adds the missing code, taking reference from a known-working `Selector` implementation in `provider-aws`.
Fixes #29
I have:
There are no existing tests for the `ResolveReferences()` methods and I have not seen any test implementations of these in other providers. I have tested the Postgres `Grant` `memberOfSelector` field on a live cluster, which is the one that was showing this issue for me originally, and these changes do fix that issue.
@srueg any chance you have a working MySQL implementation that uses …

Fix ResolveReferences on Grant types

---

pkg/controller/postgresql/role/reconciler.go
pkg/controller/postgresql/role/reconciler_test.go

When a postgres role change is detected, `provider-sql` now compares the list of provided privileges against the observed list of privileges, and only updates the privileges which have changed. This avoids throwing errors for privileges which have not actually changed (and that our non-superuser `provider-sql` user cannot change after creation).
I've added tests to confirm:
1) Only updated privileges are put into an `ALTER ROLE ...` query
2) If no privileges are changed, no query is executed
Fixes #25
I have:
Additional tests have been written as per above, and the provider has been built and run locally against the RDS postgres instance that was exhibiting the original issue to confirm that the resource is reconciled correctly.

Fix role privilege reconcile for non superusers

---

go.sum
pkg/controller/mysql/database/reconciler.go
pkg/controller/mysql/grant/reconciler.go
pkg/controller/mysql/user/reconciler.go
pkg/controller/postgresql/database/reconciler.go
pkg/controller/postgresql/grant/reconciler.go
pkg/controller/postgresql/role/reconciler.go

On clusters with a high count of resources this significantly increases
the throughput of this provider.
Also see https://github.com/crossplane/crossplane/pull/2167
Increases the max concurrency of all controllers to 5.
I have:
Locally against a kind cluster.

Increase controller max concurrency

---

apis/mysql/v1alpha1/database_types.go
apis/mysql/v1alpha1/grant_types.go
apis/mysql/v1alpha1/provider_types.go
apis/mysql/v1alpha1/user_types.go
apis/postgresql/v1alpha1/database_types.go
apis/postgresql/v1alpha1/grant_types.go
apis/postgresql/v1alpha1/provider_types.go
apis/postgresql/v1alpha1/role_types.go
package/crds/mysql.sql.crossplane.io_databases.yaml
package/crds/mysql.sql.crossplane.io_grants.yaml
package/crds/mysql.sql.crossplane.io_providerconfigs.yaml
package/crds/mysql.sql.crossplane.io_providerconfigusages.yaml
package/crds/mysql.sql.crossplane.io_users.yaml
package/crds/postgresql.sql.crossplane.io_databases.yaml
package/crds/postgresql.sql.crossplane.io_grants.yaml
package/crds/postgresql.sql.crossplane.io_providerconfigs.yaml
package/crds/postgresql.sql.crossplane.io_providerconfigusages.yaml
package/crds/postgresql.sql.crossplane.io_roles.yaml

To be able to get all managed resources of the provider-sql via `kubectl get managed` I extended all CRDs with the categories crossplane,managed,sql.
I have:
I installed the CRDs in my local cluster and verified if `kubectl get managed` results in my sql-provider managed resources.

add categories to CRDs

---

pkg/controller/postgresql/grant/reconciler.go

When creating a grant it was hard to understand that we needed two grants to add both global and database scoped privileges.
We stumbled on this error message, and had to read the sourcecode to understand why the grant was failing.
I have:

Add friendly error for memberOf grant

---

pkg/clients/postgresql/postgresql.go
pkg/controller/postgresql/database/reconciler.go
pkg/controller/postgresql/database/reconciler_test.go
pkg/controller/postgresql/grant/reconciler.go
pkg/controller/postgresql/grant/reconciler_test.go
pkg/controller/postgresql/role/reconciler.go
pkg/controller/postgresql/role/reconciler_test.go

This is in preparation for further functionality where the connection database name for the PostgreSQL client needs to be controlled dynamically, e.g. where resources must be created under a particular database. We must _connect_ on a particular database to be able to create resources on that db (e.g. Extensions).
Fixes #34
I have:
There are no tests that cover the SQL client functionality directly. 
The existing test suite still passes, and I have tested this code on a local kind cluster, both with and without overriding the database. I've also confirmed the expected behaviour when using `PGDATABASE=blah`, and making sure this is still used if an empty string is set when calling `postgresql.New()`

Allow database to be overridden in DSN from postgres constructor

---

README.md

A number of the more recently added PostgreSQL resources were missing basic examples in the README.
Signed-off-by: Ben Agricola <bagricola@squiz.co.uk>
Fixes #
I have:
N/A

Add new postgresql resource examples to readme

---

README.md

Fixes some formatting and wording in the README.md
I have:
N/A

Formatting and minor wording changes in Readme

---

pkg/controller/mysql/user/reconciler.go
pkg/controller/mysql/user/reconciler_test.go

The pointer-compare caused a panic in my test cluster, had another look at the Postgresql
cod, there the actual values are used not the pointers to compare. Also it doesn't
initialize the integer values, so removed that too.
Fixes #
I have:
Ran `make reviewable test e2e`

fix(mysql/user): correctly compare upToDate resourceOptions

---

pkg/controller/mssql/grant/reconciler.go

The TestUpdate/Success test in `pkg/controller/mssql/grant/reconciler_test.go` fails sometimes because the order of grants isn't guaranteed. This makes the condition in https://github.com/crossplane-contrib/provider-sql/blob/master/pkg/controller/mssql/grant/reconciler_test.go#L528  `false` occationally. Which for instance make the CI run in https://github.com/crossplane-contrib/provider-sql/pull/69 fail.
I have:
Ran the following before and after the fix:
```
pwd
provider-sql/pkg/controller/mssql/grant
while true; do go test -run TestUpdate/Success; done                                                           
PASS                                                                                                                                                      
ok …
```

fix(mssql/grants): Resolve TestUpdate/Success flakyness

---

pkg/controller/mysql/user/reconciler.go
pkg/controller/mysql/user/reconciler_test.go

Fixes #74
I have:
Initial commit updates the test: remove the `ResourceOptions` from the object as it is
optional, this should make the unit tests fail with a panic just as observed in #74.
Second commit checks whether the `desired.ResourceOptions` is actually set, if not it
returns as being up-to-date as we accept the defaults. This should resolve the test failures.

test(mysql/user): fail with panic, resourceOptions are optional

---

apis/mysql/v1alpha1/grant_types.go
apis/mysql/v1alpha1/zz_generated.deepcopy.go
examples/mysql/grant_table.yaml
package/crds/mysql.sql.crossplane.io_grants.yaml
pkg/controller/mysql/grant/reconciler.go
pkg/controller/mysql/grant/reconciler_test.go

Introduces support for grants by individual tables in mysql
I have:
Code was tested in local-setup with kind-cluster created with `make dev`. A local mysql-instance was connected to the provider and manual verification has been done. 
Unit-tests were part of standard-procedure.
I did *not* adjust e2e. I ran these but i think i'm missing something because it's failing with ```Error from server (BadRequest): container "provider-sql" in pod "provider-sql-provider-sql-ffb4544-6kv29" is waiting to start: ErrImageNeverPull```

Support mysql-grants by table

---

pkg/controller/postgresql/role/reconciler.go

Checks that ConfigurationParamters isn't nil before comparing.
Fixes #99
I have:
It has been tested running out of cluster

bugfix(roles.postgresql): Fix panic when taking ownership of existing role

---

cluster/local/integration_tests.sh
pkg/clients/mysql/mysql.go
pkg/clients/mysql/mysql_test.go

See https://github.com/crossplane-contrib/provider-sql/issues/98
Signed-off-by: Craig Skinfill <craig.skinfill@gmail.com>
Removes the URL escaping for the mysql password, based on https://github.com/go-sql-driver/mysql#password
Fixes #98 
I have:

no need to escape the mysql password

---

examples/postgresql/extension.yaml

The providerconfig and database names for extensions did not refer to working objects.
I have:
`kubectl apply -f examples/postgresql/`

Use matching database and providerconfig in postgresql examples

---

pkg/controller/postgresql/extension/reconciler.go

All other controllers use WithPollInterval, we've noticed bursts of
concurrent requests every minute from and this seems to be the source.
Use the same hard-coded 10 minute interval as the other controllers. We
can improve this further after upgrading provider-runtime in a subsequent PR.
I have:
Run in kind cluster

Add WithPollInterval to postgresql/extension

---

apis/mysql/v1alpha1/grant_types.go
package/crds/mysql.sql.crossplane.io_grants.yaml
pkg/controller/mysql/grant/reconciler.go
pkg/controller/mysql/grant/reconciler_test.go

Since the docs says the database is optional, I made it in the code to option, because actually if you don't pass a value this following error occurs:
```
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
...
/home/runner/work/provider-sql/provider-sql/pkg/controller/mysql/grant/reconciler.go:143 +0x98
```
This also will fix #79 and #84 
Also the documentation was updated to reflect that
I have:
I am not a go guys but when running the `make reviewable` I got this error:
```
Can't run linter unused: buildir: failed to load package goarch: could not load export data: cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool
ERRO Running error: buildir: …
```

Fixed database by passing a default value

---

pkg/controller/mysql/grant/reconciler.go
pkg/controller/mysql/grant/reconciler_test.go

If the grant is already gone when the reconciler tries to revoke it, 
it should mark the resource as successfully removed, not error.
MySQL 8.x+ supports
`REVOKE %s IF EXISTS ON %s.%s FROM %s@%s IGNORE UNKNOWN USER` 
to avoid an error (which would be a cleaner solution IMO), 
but this will only be possible when dropping support for earlier versions.
Checks the actual mysql error code that is returned when the grant
revocation SQL errors; if the code states that the grant does not exist, 
it returns `nil` for successful removal of the grant.
Basically uses the same code as  https://github.com/crossplane-contrib/provider-sql/blob/ed6c55ce4798967e7652a4cce9f844b99ac1bbb7/pkg/controller/mysql/grant/reconciler.go#L227-L231
Fixes  #47
I have:
Added unit test for this case to …

Fix Grant revocation

---

pkg/controller/mysql/grant/reconciler.go
pkg/controller/mysql/grant/reconciler_test.go

This PR mirrors https://github.com/crossplane-contrib/provider-sql/pull/139 by @Duologic.
These two PRs changed unit tests and functionality for mysql/grants
- [ Fix/grant deletion hang after user is removed error 1141 #134 ](https://github.com/crossplane-contrib/provider-sql/pull/134)
- [ Feat/mysql grant diff when updating #136](https://github.com/crossplane-contrib/provider-sql/pull/136) 
Breaking unit tests on master, this PR attempts to fix it.
I have:
```bash
make reviewable
```

Fix/consolidate unit tests for two PRs

---

apis/mysql/v1alpha1/provider_types.go
package/crds/mysql.sql.crossplane.io_providerconfigs.yaml

Fixes [#137](https://github.com/crossplane-contrib/provider-sql/issues/137)
I have:
Since the current unit tests do not setup a webhook server it kinda hard to add an automatic test for this.
Tested manually with kubectl and a local kind k8s cluster
```yaml
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
name: default
spec:
credentials:
source: MySQLConnectionSecret
connectionSecretRef:
namespace: default
name: db-conn
tls: true
```
```bash
> kubectl apply -f /home/alejandro/Documents/operators/crossplane/provider-sql/examples/mysql/config.yaml
The ProviderConfig "default2" is invalid: 
* spec.tls: Invalid value: "boolean": spec.tls in body must be of type string: "boolean"
* spec.tls: Unsupported value: true: supported values: "true", "skip-verify", …
```

Fix mysql provider config spec.tls kubebuilder validation enum

---

apis/postgresql/v1alpha1/grant_types.go
pkg/controller/postgresql/grant/reconciler.go
pkg/controller/postgresql/grant/reconciler_test.go

Inside postgresql, some privileges are [altered][0] when issuing a `GRANT`, for example `ALL` is expanded to `CREATE, TEMPORARY, CONNECT`.
When we observe the grant, we query privileges on the database to see if the ones in the grant exist. Given that they are expanded, we can't simply query for what the user gave us. Expand the privileges which need expanding before we make the query.
Closes: #92
[0]: https://www.postgresql.org/docs/15/ddl-priv.html
* There's a unit test to check the permissions are expanded
* We extracted the queries the provider is using and ran them manually against a database

postgres: Expand grant privileges where required

---

pkg/controller/mysql/grant/reconciler.go
pkg/controller/mysql/grant/reconciler_test.go

Fixes #128
This PR cherry-picks the commits from #132 (all credit goes to the author) and fixes the merge conflicts with master.
I have:
Quoting from https://github.com/crossplane-contrib/provider-sql/pull/132
> Added unit tests to grant controller:
> 
> * Observe method:
>   * SuccessGrantOptionNoDatabase
>   * SuccessGrantOptionWithDatabase
> * Create method:
>   * SuccessGrantOption
> * Update method:
>   * SuccessGrantOption

Support MySQL `WITH GRANT OPTION` (cherry-picks #132)

---

.github/workflows/promote.yml

Fixes the CI job to promote this provider to the marketplace.

ci: promote to upbound marketplace

---

README.md
examples/deploymentRuntimeConfig.yaml
examples/provider.yaml

Add provider-sql installation guidance for newcomers.
This PR also add an very small example for a provider configuration with the deploymentRuntimeConfig resource.
Fixes #163
I have:

chore: add provider install documentation

---

pkg/clients/mysql/mysql.go
pkg/clients/mysql/mysql_test.go
pkg/controller/mysql/database/reconciler.go
pkg/controller/mysql/database/reconciler_test.go
pkg/controller/mysql/grant/reconciler.go
pkg/controller/mysql/grant/reconciler_test.go
pkg/controller/mysql/user/reconciler.go
pkg/controller/mysql/user/reconciler_test.go

Fixes #170
As actual MySQL code is not designed to execute several statements in the same connection, the `sql_log_bin` parameter value is now given at [DSN level](https://github.com/go-sql-driver/mysql/tree/v1.5.0?tab=readme-ov-file#system-variables). This ensures this parameter is always taken into account, no matter how MySQL connections are managed under the hood.
I guess this could be fixed differently, but it's the simpler way I found to manage this. Any feedbacks are welcome.
I have:
I created several `User` and `Grant` resources against a MySQL 8.0 server, with and without binlog option enabled, and then I check what was written in binlog files. It worked as expected.

Give MySQL sql_log_bin at DSN level to take parameter into account

---

apis/mssql/v1alpha1/grant_types.go
apis/mssql/v1alpha1/zz_generated.deepcopy.go
package/crds/mssql.sql.crossplane.io_grants.yaml
pkg/controller/mssql/grant/reconciler.go
pkg/controller/mssql/grant/reconciler_test.go

This pull request allows to create MSSQL grants on Schemas not only on the database.
A new optional `schema` is introduced. If defined, the grants will be created for this schema.
I have:
Tested on a local Cluster with a patched image using the following resoruces.
```
apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
name: sql-example-grant
spec:
forProvider:
database: test-db
permissions:
- CONNECT
- CREATE TABLE
- INSERT
- SELECT
userRef:
name: sql-example-user
providerConfigRef:
name: test-db
---
apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
name: sql-example-grant-dbo
spec:
forProvider:
schema: dbo
database: test-db
permissions:
- ALTER
userRef:
name: sql-example-user
providerConfigRef:
name: test-db
```
[contribution process]: …

add support for MSSQL schema in grants

---

apis/mysql/v1alpha1/database_types.go
apis/mysql/v1alpha1/grant_types.go
apis/mysql/v1alpha1/user_types.go
pkg/clients/mysql/mysql.go
pkg/clients/mysql/mysql_test.go

The MySQL binlog parameter in dsn (connection string) is currently mandatory, but this causes errors like
_Error 1227: Access denied; you need (at least one of) the SUPER, BINLOG ADMIN privilege(s) for this operation_ 
with AWS RDS MariaDB and default admin user.
Binlog parameter for Users, Grants and Databases becomes optional and does not have a default value at all.
In this way, the `sql_bin_log` parameter in DSN becomes optional and it is added only when binlog is explicitly set to true/false in one of the managed resources.
Fixes the side effect of #171 in AWS RDS MariaDB.
I have:
Unit tests updated and added one more to cover the new case of missing binlog.
Tested with AWS RDS Mariadb: provisioned users, databases and grants.

optional binlog parameters in mysql connection string

---

cluster/local/integration_tests.sh

We encountered the following error in the CI pipeline on master.
```
>>>>>>> installing MariaDB with no TLS
secret/mariadb-creds created
index.go:346: skipping loading invalid entry for chart "airflow" "" from https://charts.bitnami.com/bitnami: validation: chart.metadata.name is required
index.go:346: skipping loading invalid entry for chart "airflow" "" from /home/runner/.cache/helm/repository/bitnami-index.yaml: validation: chart.metadata.name is required
Error: INSTALLATION FAILED: failed to download "bitnami/mariadb" at version "11.3.0"
```
Fixes #
Apply a helm repo update before installing.
I have:
- [ x ] Read and followed Crossplane's [contribution process].
- [ x ] Run `make reviewable` to ensure this PR is ready for review.
```
make clean
make build
make reviewable
make e2e
``` …

update helm repo before intalling mariadb

---

OWNERS.md

Carl has been a solid contributor and would like to help out more. This PR adds him to the maintainers list in OWNERS.md.

chore: add chlunde to maintainers list

---

.github/workflows/ci.yml

Update upload-artifact action
I have:

bump github actions upload-action to latest release due to deprecation

---

.github/workflows/backport.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/commands.yml
.github/workflows/promote.yml
.github/workflows/tag.yml
.golangci.yml
Makefile
pkg/controller/mssql/grant/reconciler_test.go
pkg/controller/mysql/grant/reconciler_test.go

`make lint` command prompts deprecation warnings and fails to succeed with the current settings, mainly due to deprecated linters. This PR bumps golangci version and replaces some linters with the suggested alternatives, while sticking as much as possible to the original settings.
Fixes #
I have:
`make lint`

chore: bump golangci version

---

.github/workflows/ci.yml
go.mod

Go 1.23.9 is a security update, and we also need to update
Go to get dependabot security updates out (dependabot does not
run 'go mod tidy').
I have:
`make && make e2e`

chore: Update Go to 1.23.9

---

cluster/local/postgresdb_functions.sh
examples/postgresql/database.yaml

Add basic coverage of managementPolicies to e2e tests. I've only covered one resource as this is code managed i crossplane-runtime, but we want to ensure everything is wired correctly.
I have:
e2e tests

test: add coverage of managementPolicies to e2e

---

Makefile
cluster/local/integration_tests.sh

Remove duplicate and overridden entry of golangci-lint version from Makefile, most possibly a leftover from the last PRs.
Fixes #
I have:
make reviewable test

chore: remove duplicate entry of golangci version

---

apis/mysql/v1alpha1/database_types.go
package/crds/mysql.sql.crossplane.io_databases.yaml

This was a breaking change which was not strictly required. Make the
field optional again so we don't cause any uneccesary breaking changes
for users upgrading from 0.7.0.
Thanks to @cm3brian for the report!
Fixes #241
I have:
Should be covered by e2e tests. The field is not a pointer so everything should behave identical to how it works already. 

Relax MySQL Database schema, forProvider is optional
