crossplane-contrib/provider-sql

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/stale.yml, .github/workflows/ci.yml, .github/workflows/promote.yml, .github/workflows/tag.yml
As copied from https://github.com/crossplane-contrib/provider-helm
=> Add GitHub Actions Setup

package/crossplane.yaml
=> Create a provider package

.golangci.yml, Makefile, cluster/images/provider-sql/Dockerfile, cluster/images/provider-sql/Makefile, cluster/local/integration_tests.sh
Implement e2e integration tests.
I have:
`make e2e.run`
=> Implement integration tests

pkg/clients/sql/common.go, pkg/clients/sql/mysql.go, pkg/clients/sql/postgresql.go, pkg/controller/mysql/database/reconciler.go, pkg/controller/mysql/database/reconciler_test.go, pkg/controller/postgresql/database/reconciler.go, pkg/controller/postgresql/database/reconciler_test.go
Refactor the reconcilers and introduce a dedicated `clients` package.
I have:
Manually on a Kind cluster
=> Refactor Reconcilers

cluster/local/integration_tests.sh, examples/mysql/database.yaml, examples/mysql/user.yaml, pkg/controller/mysql/user/reconciler.go
Fixes some errors in escaping of values in queries. Mainly regarding the user/host syntax.
I have:
`make test`
`make build e2e.run`
=> Fix quotes in MySQL queries

cluster/local/integration_tests.sh
Bumps Provider to v1beta1 version so that it remains compatible with
latest crossplane versions.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
I have:
n/a
=> Use v1beta1 Provider in integration tests

apis/mysql/v1alpha1/database_types.go, apis/mysql/v1alpha1/grant_types.go, apis/mysql/v1alpha1/provider_types.go, apis/mysql/v1alpha1/user_types.go, apis/mysql/v1alpha1/zz_generated.deepcopy.go, apis/mysql/v1alpha1/zz_generated.managed.go, apis/mysql/v1alpha1/zz_generated.pc.go, apis/mysql/v1alpha1/zz_generated.pcu.go, apis/postgresql/v1alpha1/database_types.go, apis/postgresql/v1alpha1/provider_types.go, apis/postgresql/v1alpha1/zz_generated.deepcopy.go, apis/postgresql/v1alpha1/zz_generated.managed.go, apis/postgresql/v1alpha1/zz_generated.pc.go, apis/postgresql/v1alpha1/zz_generated.pcu.go, go.mod, go.sum, pkg/clients/mysql/mysql.go, pkg/clients/postgresql/postgresql.go, pkg/controller/mysql/database/reconciler.go, pkg/controller/mysql/database/reconciler_test.go, pkg/controller/mysql/grant/reconciler.go, pkg/controller/mysql/grant/reconciler_test.go, pkg/controller/mysql/user/reconciler.go, pkg/controller/mysql/user/reconciler_test.go, pkg/controller/mysql/user/utils.go, pkg/controller/postgresql/database/reconciler.go, pkg/controller/postgresql/database/reconciler_test.go
I have:
It has not - it's a very mechanical change.
=> Bump crossplane-runtime to v0.12.0

cluster/local/integration_tests.sh, package/crossplane.yaml
Per crossplane/crossplane#2299
Note there's currently no icon for provider-sql.
I have:
=> Add recommended package metadata

cluster/local/integration_tests.sh, package/crossplane.yaml
Backport of https://github.com/crossplane-contrib/provider-sql/pull/43 (into this as yet unreleased release branch)
I have:
=> [release-0.2] Add recommended package metadata

OWNERS.md
I haven't had time to commit to this repo, and they volunteered! Thank you folks. Also thank you to Ben and Simon, who made a lot of great contributions but I believe have moved on from maintaining this repo.
I'm leaving myself in as a maintainer largely because I believe there are some things I may need to help with permissions wise going forward.
I have:
N/A
=> Make Duologic and jdotw maintainers

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, Makefile, cluster/local/integration_tests.sh, package/crds/mssql.sql.crossplane.io_databases.yaml, package/crds/mssql.sql.crossplane.io_grants.yaml, package/crds/mssql.sql.crossplane.io_providerconfigs.yaml, package/crds/mssql.sql.crossplane.io_providerconfigusages.yaml, package/crds/mssql.sql.crossplane.io_users.yaml, package/crds/mysql.sql.crossplane.io_databases.yaml, package/crds/mysql.sql.crossplane.io_grants.yaml, package/crds/mysql.sql.crossplane.io_providerconfigs.yaml, package/crds/mysql.sql.crossplane.io_providerconfigusages.yaml, package/crds/mysql.sql.crossplane.io_users.yaml, package/crds/postgresql.sql.crossplane.io_databases.yaml, package/crds/postgresql.sql.crossplane.io_extensions.yaml, package/crds/postgresql.sql.crossplane.io_grants.yaml, package/crds/postgresql.sql.crossplane.io_providerconfigs.yaml, package/crds/postgresql.sql.crossplane.io_providerconfigusages.yaml, package/crds/postgresql.sql.crossplane.io_roles.yaml
The lint CI job was consistently failing, this PR pulls in changes from upbound/build and
crossplane/provider-template to mitigate that failure.
I have:
Tested fix for reproducible failure on #87
=> fix(ci): lint

cluster/local/integration_tests.sh
The current chart does not seem to exist anymore (as reported in #97, this should fix
that.
I have:
Run e2e test
=> fix(integration): update mariaDB chart

cmd/provider/main.go, pkg/controller/mssql/config/config.go, pkg/controller/mssql/database/reconciler.go, pkg/controller/mssql/grant/reconciler.go, pkg/controller/mssql/mssql.go, pkg/controller/mssql/user/reconciler.go, pkg/controller/mysql/config/config.go, pkg/controller/mysql/database/reconciler.go, pkg/controller/mysql/grant/reconciler.go, pkg/controller/mysql/mysql.go, pkg/controller/mysql/user/reconciler.go, pkg/controller/postgresql/config/config.go, pkg/controller/postgresql/database/reconciler.go, pkg/controller/postgresql/extension/reconciler.go, pkg/controller/postgresql/grant/reconciler.go, pkg/controller/postgresql/postgresql.go, pkg/controller/postgresql/role/reconciler.go, pkg/controller/sql.go
Add option to change the poll interval
I have:
=> add option to configure polling interval

pkg/controller/mysql/grant/reconciler.go
Fixes incomplete changes to https://github.com/crossplane-contrib/provider-sql/pull/148
I have:
=> fix: correctly set GRANT OPTION privilege

OWNERS.md
Adds additional maintainers, both have made contributions to improve the provider.
cc/ @jvrplmlmn @iainlane
=> chore: add maintainers

Makefile
Fixes the CI on master, it doesn't have credentials anymore to push to Docker hub, which is fine.
I have:
Merge to master can test this properly.
=> ci: only push to Upbound marketplace

examples/postgresql/config.yaml
It didn't work until I change the `host` with `endpoint` while deploying Postgres using CloudNativePG Kubernetes operator under the hood.
I have:
=> change the host with endpoint to make it worked

pkg/clients/mysql/mysql.go, pkg/controller/mysql/database/reconciler.go, pkg/controller/mysql/grant/reconciler.go, pkg/controller/mysql/user/reconciler.go
=> fix: remove unneeded flush privileges call for mysql

.github/workflows/backport.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/commands.yml, .github/workflows/promote.yml, .github/workflows/tag.yml, .gitmodules, Makefile, cluster/local/integration_tests.sh
Just updating our build tooling, housekeeping.
This PR brings CI and scripts up-to-date with the https://github.com/crossplane/provider-template repo and pulls in a new version of `build/` from https://github.com/crossplane/build
=> chore: update build/ and Makefile

OWNERS.md
=> Move negz to emeritus status
